export const CommonStrings = {
  login: 'Login',
  countryCode: '+91',
  continue: 'Countinue',
  signUpOption: '-----Or sign up with-----',
  haveNotAccount: 'Dont have an account ? ',
  register: 'Register',
  createNewAc: 'Create New Account',
  name: 'Name',
  email: 'Email',
  phoneNumber: 'Phone Number',
  haveAC: 'Already have an account ? ',
  instruction:
    'By clicking create new account you agree to the following Terms & Condition.',
  verificationHeader: 'OTP Verification',
  otpInstruction: 'Your Otp Verification code Sent to your Mobile Number',
  dontReceiveCode: "Didn't receive the code ",
  resend: 'Resend',
  home: 'home',
  topSalon: 'Top Salon',
  location: 'Mong Kok Flower Market',
  topService: 'Top Services',
  viewAll: 'View All',
  palce: 'Place',
  ourProduct: 'Our Product',
  filter: 'Filter',
  get: 'Get',
  discountFor: 'Discount for',
  buyNow: 'Buy now',
  salon: 'Salon',
  PR: ' 2%',
  book: 'Book',
  service: 'Service',
  product: 'Product',
  about: 'About',
  gallary: 'Gallery',
  hk$: 'HK$ ',
  time: ' / min',
  taxInfo: 'inc. of all taxes',
  price: 16,
  Features: 'Features',
  Specification: 'Specification',
  productType: 'ProductTypeName : ',
  beauty: 'BEAUTY',
  Publisher: 'Publisher : ',
  kerastase: 'Kerastase',
  releaseDate: 'ReleaseDate : ',
  date: '2014-06-27',
  size: 'Size : ',
  sizeNo: '6.8 oz.',
  SKU: ' SKU',
  skuNo: '3474630477056-200ml',
  studio: 'Studio',
  studioName: 'Kerastase',
  title: 'Title',
  oilMaskName: ' Kerastase Elixir Ultime Beautifying Oil Masque, 6.8 Ounce',
  add: 'Add',
  weekDays: 'Monday - Thursday',
  weekEnds: 'Friday - Sunday',
  weekDaysTime: '8:30 AM - 9:00 PM',
  weekEndsTime: '10:00 AM - 2:00 PM',
  locationTxt:'Location',
  aboutSalon:
    'Located in the heart of the city, Le Spa by Jan is an independent, high-quality spa with a passionate skilled team offering a calm retreat away from the hustle and bustle of HK. As a boutique Spa, we believe in excellency in service, unique care, specially selected products yet affordable prices.',
salonLocation:'2/F Stanley 11, No. 11 Stanley Street, Hong Kong China',
km:'2.5 km',
};
